services:
   postgres:
     image: postgres:15
     container_name: urlshortener-postgres
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: 1234
       POSTGRES_DB: urlshortener
     ports:
       - "5432:5432"
     volumes:
       - postgres-data:/var/lib/postgresql/data

volumes:
   postgres-data:
